# See http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "0.11"
before_install: npm install -g grunt-cli
install:
  - npm install
  - grunt install
before_script:
  - grunt build
after_success:
 - cat ./coverage/lcov.dat | ./node_modules/coveralls/bin/coveralls.js
# Remove "after_script" once the tests all pass to run docs in "after_success".
after_script:
  - grunt doc

# Deploy JSDocs to S3 static site
deploy:
  provider: s3
  access_key_id: AKIAJLMFT7PREEIB7JSQ
  # secret_access_key: <encrypted>
  bucket: atlas-jsdocs
  skip_cleanup: true
  local-dir: jsdocs
  endpoint: atlas-jsdocs.s3-website-ap-southeast-2.amazonaws.com
  region: ap-southeast-2

# Contains the S3 secret access key.
env:
  global:
    secure: QYHf+o0sIfCD/qh7BgcG1BMh7NSdT/6ELY30uGHqonOZ8xzuNb+QwMzImQAuzo1TCxvJMHFFQVQ2KHEb7bVG5NNHLh6fp7MoMsuylJcxgJNbFmZTpaAEzLd7HAFhzdMKEGPErfV/q+IOqsJAoImdHqjHUohNahSpwsbROb1ioH0=
