# See http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "0.11"
before_install: npm install -g grunt-cli
install:
  - npm install
  - grunt install
before_script:
  - grunt build
script:
  - echo "skipping tests"
after_success:
  - cat ./coverage/lcov.dat | ./node_modules/coveralls/bin/coveralls.js
  - grunt doc

# Deploy JSDocs to S3 static site
deploy:
  provider: s3
  access_key_id: AKIAJLMFT7PREEIB7JSQ
  secret_access_key:
    secure: WKf+D1FEND54BsA1xVK4XsxpF9wXcqXbOHmPBOESqu5Fs7vGYl85ouqkVaZBPdBFKFcKPHHCPP6gNxrcy4xcgtLwhPNDmAfQiyrfTnyJIEQaD0ON1tPvr0D+XF3MSWC9IEqB8fyRLLam782BoCv8fJDBtShdUNoCKw5IreH+PjM=
  bucket: atlas-jsdocs
  acl: public_read
  endpoint: atlas-jsdocs.s3-website-ap-southeast-2.amazonaws.com
  region: ap-southeast-2
  local-dir: jsdocs
  skip_cleanup: true
  on:
    all_branches: true
#    tags: true
